language: java
jdk: oraclejdk8
services: mongodb

before_install:
- mvn clean

install:
- npm install
- npm run-script build
- mvn install

script:
- mvn test
- npm test

after_success:
- (echo ${SERVER_PASSWORD}) | scp -o "StrictHostKeyChecking no" target/webpage-0.0.1.jar root@5.231.53.194:/root/CoinbaseTraders/production/CoinbaseTraders.jar
- (echo ${SERVER_PASSWORD}) | ssh -o "StrictHostKeyChecking no" root@5.231.53.194 "cd /root/CoinbaseTraders && ./restart_production.sh"