language: java
jdk: oraclejdk8
services: mongodb

before_install:
- mvn clean

install:
- mvn install
- npm install
- npm run-script build

script:
- mvn test
- npm test

after_success:
- echo 'DEPLOY TODO'