language: java
jdk: openjdk8
services: mongodb

before_install:
- mvn clean
- npm install

install:
- mvn install

before_script:
- grunt build

script:
- mvn test
- grunt test

after_success:
- echo 'DEPLOY TODO'