language: java
jdk: oraclejdk8
services: mongodb

addons:
  code_climate:
    repo_token:
      secure: "WyEdZGN/A9AuLfa1CnQOXGchAH8Zl94WbW+YgCozVIDzY+0dfpedUUeQEqFwhbVwpQYNW9DkPkM45cHgUFbYrbPMSfshm5X6hNpCu86N3wJT6tPxLCNWC1LAanflGgVqHwm2ARELxyBa8bIfFNsw29Wkz8cVX8jpHhAYbJs040k="

virtualenv:
  system_site_packages: true

before_install:
- mvn clean
- sudo apt-get install -qq sshpass
install:
- npm install
- npm run-script build
- mvn install
script:
- mvn test
- npm test
after_success:
- sshpass -p ${SERVER_PASSWORD} scp -o "StrictHostKeyChecking no" target/webpage-0.0.1.jar
  root@5.231.53.194:/root/CoinbaseTraders/test/CoinbaseTraders.jar
- sshpass -p ${SERVER_PASSWORD} ssh -o "StrictHostKeyChecking no" root@5.231.53.194
  "cd /root/CoinbaseTraders && ./restart_test.sh"
after_script:
- cat logs/coverage/lcov.info | npm run-script analyse
